modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
[[mods]]
modId = "constructionfoam"
version = "${file.jarVersion}"
displayName = "Construction Foam"
authors = "Grimmauld, Kayla"
description = '''Construction foam mod to fill big voids with ease
'''
[[dependencies.constructionfoam]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.constructionfoam]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
